Title: IBM Warning displayed in status pane when starting Case Foundation Case Analyzer, after installing IBM FileNet Case Analyzer (CA) - United States

Text:
Process Engine; database; analyzer.properties TECHNOTE (TROUBLESHOOTING)

PROBLEM(ABSTRACT)
 Warning displayed in status pane when starting Case Foundation Case Analyzer, after installing IBM FileNet Case Analyzer (CA) 

SYMPTOM
Warning displayed in status pane when starting Case Analyzer, after installing IBM FileNet Case Analyzer (CA):

Unable to synchronize PE database with PA event state.

com.ibm.db2.jcc.a.sm: [jcc][t4][2057][11264][3.51.90] The application server rejected establishment of the connection.

An attempt was made to access a database, CATest, which was either not found or does not support transactions. ERRORCODE=-4499, SQLSTATE=08004

at com.ibm.db2.jcc.a.wc.a(wc.java:267)

at com.ibm.db2.jcc.a.wc.a(wc.java:303)

at com.ibm.db2.jcc.t4.bb.u(bb.java:1624)

at com.ibm.db2.jcc.t4.bb.n(bb.java:521)

at com.ibm.db2.jcc.t4.bb.a(bb.java:328)

at com.ibm.db2.jcc.t4.bb.a(bb.java:111)

at com.ibm.db2.jcc.t4.b.i(b.java:1285)

at com.ibm.db2.jcc.t4.b.b(b.java:1168)

at com.ibm.db2.jcc.t4.b.c(b.java:723)

at com.ibm.db2.jcc.t4.b.b(b.java:709)

at com.ibm.db2.jcc.t4.b.a(b.java:393)

at com.ibm.db2.jcc.t4.b.<init>(b.java:331)

at com.ibm.db2.jcc.DB2Driver.connect(DB2Driver.java:193)

at java.sql.DriverManager.getConnection(DriverManager.java:562)

at java.sql.DriverManager.getConnection(DriverManager.java:186)

at filenet.pa.sql.DBConnectionManager.createPEConnection(Unknown Source)

at filenet.pa.sql.DBConnectionManager.getNewPEConnection(Unknown Source)

at filenet.pa.datacollector.ConfigurationInfoAgent.getTableOwner(Unknown Source)

at filenet.pa.sql.PADataEnvironmentBase.updateVWPAEventState(Unknown Source)

at filenet.pa.main.Main.main(Unknown Source)


CAUSE
The Case Analyzer database name is specified instead of the Process Engine database during the installation of CA.

RESOLVING THE PROBLEM
Locate the following parameter "analyzer.pedb.name=" parameter in the analyzer.properties file and verify that the Process Engine database is specified and not the Case Analyzer database. 
If the incorrect database is specified launch the Case Analyzer Process Task Manager select the Process Engine Database tab and enter the correct Database Name for the Process Engine. 

[/support/docview.wss?uid=swg21677024&aid=1] [/support/docview.wss?uid=swg21677024&aid=1]