Title: IBM LDAP group synchronization failed with error "BMXAA6772W" - United States

Text:
LDAPSYNC; BMXAA6772W; userPrincipalName; TPAELDAP TECHNOTE (TROUBLESHOOTING)

PROBLEM(ABSTRACT)
 LDAP group synchronization failed with the error "BMXAA6772W - Group members could not be retrieved from the LDAP context" 

SYMPTOM
00000540 SystemOut [ERROR] BMXAA6752E - Group synchronization could not be performed because of error BMXAA6772W - Group members could not be retrieved from the LDAP context.. The error count was 29. 

psdi.security.ldap.LdapSyncException: BMXAA6772W - Group members could not be retrieved from the LDAP context.
at psdi.security.ldap.ads.ActiveDirectorySynchronizer.retrieveGroupMembers(ActiveDirectorySynchronizer.java:482)
at psdi.security.ldap.ads.ActiveDirectorySynchronizer.retrieveAllGroupMembers(ActiveDirectorySynchronizer.java:337)
at psdi.security.ldap.AbstractLdapSynchronizer.syncGroups(AbstractLdapSynchronizer.java:1165)
at psdi.security.ldap.AbstractLdapSynchronizer.performSync(AbstractLdapSynchronizer.java:321)
at psdi.security.ldap.LdapSyncTask.performTask(LdapSyncTask.java:386)
at psdi.security.ldap.LdapSyncCronTask.cronAction(LdapSyncCronTask.java:257)
at psdi.server.CronTaskManager.callCronMethod(CronTaskManager.java:1575)
at psdi.server.CronTaskManager.access$400(CronTaskManager.java:83)
at psdi.server.CronTaskManager$CronThread.run(CronTaskManager.java:2093)
Caused by: 
java.lang.NullPointerException
at psdi.security.ldap.ads.ActiveDirectorySynchronizer.getMemberUserAccountName(ActiveDirectorySynchronizer.java:537)
at psdi.security.ldap.ads.ActiveDirectorySynchronizer.retrieveGroupMembers(ActiveDirectorySynchronizer.java:421)
... 8 more


ENVIRONMENT
MS Active Directory for LDAP Server


RESOLVING THE PROBLEM
Through LDAPSYNC Crontask, Users, Groups and Group Users will be synchronised between Maximo and the MS Active Directory LDAP Server. 

When the group synchronisation task is running, Maximo will synchronise member users belonging to each group. 

According to the error message above, a NullPointerException error occurs when getting member users belonging to a group. 

This error is caused by a missing attribute for users information in MS Active Directory. 

Steps to resolve this problem: 

1. Check the GroupMapping parameter in LDAPSYNC crontask definition.
<<
~~~~
<memberdatamap><membertable name="GROUPUSER"><keycolumn name="GROUPNAME" type="ALN">cn</keycolumn>\<membercolumn name="USERID" type="UPPER"><member>member</member><memberuser>userPrincipalName</memberuser><membergroup>cn</membergroup></membercolumn><column name="GROUPUSERID" type="INTEGER">{:uniqueid}</column></membertable></memberdatamap> 
</group></ldapsync> 

>> 

As you can see from the GroupMapping parameter above, Maximo will try to get the userPrincipalName attribute's value as group member users. 

2. Check if there is any missing data in MS Active Directory user information. 

For example, like Maxadmin user below, the userPrincipalName attribute for the user should exist. 
[/support/docview.wss?uid=swg21516474&aid=1] [/support/docview.wss?uid=swg21516474&aid=1] 

 

If there are any users that do NOT have a userPrincipalName attribute/value, you will then get a BMXAA6772W error. Finally, LDAPSYNC will fail. 

The problem will be fixed after adding the userPrincipalName attribute and a value.