Title: IBM J2CA0092E and J2CA0009E with java.lang.Exception: Failed security check - United States

Text:
 TECHNOTE (TROUBLESHOOTING)

PROBLEM(ABSTRACT)
 You see a J2CA0092E or J2CA0009E with java.lang.Exception: Failed security check. 

SYMPTOM
[11/17/08 14:40:48:806 CST] 416509f3 ConnectionFac E J2CA0092E: This is
an English only message: Failed security check. Client is not
permitted to create connection factory jdbc/TestDS.[</code>] 


[11/17/08 14:40:48:884 CST] 416509f3 ConnectionFac E J2CA0009E: An
exception occurred while trying to instantiate the
ManagedConnectionFactory class
com.ibm.ws.rsadapter.spi.WSManagedConnectionFactoryImpl used by
resource jdbc/BPEDB : java.lang.Exception: Failed security check.
Client is not permitted to create connection factory jdbc/TestDS. 




CAUSE
This error indicates that authentication alias specified in the data source or QCF configuration does not exist on the JVM that is trying to get the connection. This might occur if the data source configuration in the resources.xml file is created with a wsadmin script or if it is copied from resources.xml from one JVM to another manually, but the Javaâ„¢ 2 Connector (J2C) authentication data entries in the security.xml file are not copied. The data source factory definition has the container-managed authentication alias value set to node_name/TestDsAlias as shown in the following example, but no J2C authentication data entry node_name/TestDsAlias defined in the security.xml file: 

RESOLVING THE PROBLEM
Replace the authDataAlias, "node_name/TestDsAlias", with a J2C authentication alias that is configured on this system and that has the right username and password for the connection.

 Stack from the SystemOut . [4/1/04 13:15:23:034 CST] 761c56 Helpers W NMSV0610I: A NamingException is being thrown from a javax.naming.Context implementation. Details follow: Context implementation: com.ibm.ws.naming.jndicos.CNContextImpl Context method: lookup Context name: test1Network/nodes/test1/servers/test1_testejb Target name: jdbc/TestDS Other data: Exception stack trace: com.ibm.websphere.naming. CannotInstantiateObjectException: Exception occurred while the JNDI NamingManager was processing a javax.naming.Reference object. Root exception is java.lang.Exception: Failed security check. Client is not permitted to create connection factory jdbc/TestDS at com.ibm.ejs.j2c.ConnectionFactoryBuilderImpl.createMCFandPM (ConnectionFactoryBuilderImpl.java:1566) at com.ibm.ejs.j2c.ConnectionFactoryBuilderImpl. getObjectInstance(ConnectionFactoryBuilderImpl.java:1188) at javax.naming.spi.NamingManager.getObjectInstance (NamingManager.java:299) at com.ibm.ws.naming.util.Helpers. processSerializedObjectForLookup(Helpers.java:884) at com.ibm.ws.naming.jndicos.CNContextImpl.processResolveResults (CNContextImpl.java:1762) at com.ibm.ws.naming.jndicos.CNContextImpl.doLookup (CNContextImpl.java:1615) at com.ibm.ws.naming.jndicos.CNContextImpl.doLookup (CNContextImpl.java:1525) at com.ibm.ws.naming.jndicos.CNContextImpl.lookup(CNContextImpl. java:1225) at com.ibm.ws.naming.util.WsnInitCtx.lookup(WsnInitCtx.java:132) at javax.naming.InitialContext.lookup(InitialContext.java:345) ...

Cross reference information Segment Product Component Platform Version Edition Application Servers Runtimes for Java Technology Java SDK