Title: IBM Hypervisors are not listed in the IBM SmartCloud Orchestrator user interface - United States

Text:
hypervisor; CWZCO1007E; SQLCODE=-302; 302; -302; CWZCL3165E TECHNOTE (TROUBLESHOOTING)

PROBLEM(ABSTRACT)
 After a new region is installed, you cannot see any hypervisors listed in the IBM SmartCloud Orchestrator user interface. 

CAUSE
There is a problem with storing the hypervisor in the database due to the limited length of the column. 

DIAGNOSING THE PROBLEM
The following messages are seen in the IBM Workload Deployer trace.log file:

[2014-06-05 12:55:05:020 EDT] 00000664 groovy E
app.scripts.groovy.rainmaker.core.SQLUtils.groovy CWZCO1007E: Could not
create resource: [pdq][10104][2.7.116] An error prevented the update
operation from completing successfully.; Caused by:
com.ibm.db2.jcc.am.SqlDataException: DB2 SQL Error: SQLCODE=-302,
SQLSTATE=22001, SQLERRMC=null, DRIVER=4.14.113
[2014-06-05 12:55:05:127 EDT] 00000664 groovy E
app.scripts.groovy.rainmaker.core.SQLUtils.groovy
com.ibm.pdq.runtime.exception.DataRuntimeException:
[pdq][10104][2.7.116] An error prevented the update operation from
completing successfully.; Caused by:
com.ibm.db2.jcc.am.SqlDataException: DB2 SQL Error: SQLCODE=-302,
SQLSTATE=22001, SQLERRMC=null, DRIVER=4.14.113
com.ibm.pdq.runtime.internal.db.JdbcData.update_(JdbcData.java:438)
com.ibm.pdq.runtime.internal.db.DataImpl.update(DataImpl.java:545)
zero.data.Manager.insert(Manager.java:1605)
zero.data.groovy.Manager.insert(Manager.java:1448)
groovy.rainmaker.core.SQLUtils._createResource(SQLUtils.groovy:90)

groovy.rainmaker.core.SQLUtils$_createResource_closure4.doCall(SQLUtils.
groovy:67)

groovy.rainmaker.core.SQLUtils$_createResource_closure4.doCall(SQLUtils.
groovy)
....................
clouds.onRetrieve(clouds.groovy:439)
Caused by: com.ibm.db2.jcc.am.SqlDataException: DB2 SQL Error:
SQLCODE=-302, SQLSTATE=22001, SQLERRMC=null, DRIVER=4.14.113
com.ibm.db2.jcc.am.ed.a(ed.java:669)
com.ibm.db2.jcc.am.ed.a(ed.java:60)
com.ibm.db2.jcc.am.ed.a(ed.java:127)
com.ibm.db2.jcc.am.oo.c(oo.java:2715)
com.ibm.db2.jcc.am.oo.a(oo.java:2163)
com.ibm.db2.jcc.t4.ab.o(ab.java:844)
com.ibm.db2.jcc.t4.ab.j(ab.java:266)
.............
[2014-06-05 12:55:05:212 EDT] 00000664 groovy E
app.scripts.groovy.rainmaker.cloud.VMSupportAccess.groovy CWZCL3165E:
An access attempt failed for hypervisor ID 821, address
https://IBMTestmountain01_ibmlu001-a@ibm0001vmibm001.itservices.ibm.com-443:java.lang.Exception: 

Within the previous messages, you can see the internal database error.

RESOLVING THE PROBLEM
To resolve this problem, you can delete the region and create it with the shortest possible name. With this approach, the hypervisors will fit into the 64 characters limit (for example, 63 characters).

If that approach is not possible, another option is to delete and create the cloud/vilproxy definitions using the Virtual Center IP address versus the host name. The name values are shorter in this case.



The following example shows the long external_uri value, which causes the problem:
./nova-cloud-show

{"username": "Itservices\\IBM259"
"jmsPort": 61617
"name": "IBMTestmountain01"
"hostname": "ibm0001vmibm001.itservices.ibm.com"
"port": 443
"state":
{"id": "OK"
"label": "OK"}
"cloudType": "VMware"
"timeout": 600
"external_uri": "ibm0001vmibm001.itservices.ibm.com:443"
"id": "ibmv0011:4051"
"description": "OpenStack managed VMware"}


The following example shows the Virtual Center IP address used for the external_uri value: 

./nova-cloud-show

{"username": "Itservices\\IBM259"
"jmsPort": 61617
"name": "IBMTestmountain01"
"hostname": "9..32.33.134"
"port": 443
"state":
{"id": "OK"
"label": "OK"}
"cloudType": "VMware"
"timeout": 600
"external_uri": "9.32.33.134:443"
"id": "ibmv0011:5651"
"description": "OpenStack managed VMware"}

As a result, all the hypervisor definitions will now fit.