Title: IBM Unable to process cube after deploying a user-defined data field. - United States

Text:
user-defined data field; deployment; PA; process cube; rebuild database views TECHNOTE (TROUBLESHOOTING)

PROBLEM(ABSTRACT)
 After deploying a custom data field in the queue, roster and Process Analyzer (PA), the PA stopped functioning, and a error was thrown when launching the operation "Start / Process Cube" in the Process Task Manager (PTM). 

SYMPTOM
The error reads:
2010/12/13 09:54:52 [filenet.pa.datacollector.EventDispatcher - 1] SEVERE datacollector Event dispatcher thread 1 work on view VWVL1_DEFAULTEVENTLOG: Database error:
com.ibm.db2.jcc.am.io: DB2 SQL Error: SQLCODE=-206, SQLSTATE=42703, SQLERRMC=F_SeqNumber, DRIVER=3.57.82
at com.ibm.db2.jcc.am.bd.a(bd.java:676)
at com.ibm.db2.jcc.am.bd.a(bd.java:60)
at com.ibm.db2.jcc.am.bd.a(bd.java:127)
at com.ibm.db2.jcc.am.km.c(km.java:2506)
at com.ibm.db2.jcc.am.km.d(km.java:2483)
at com.ibm.db2.jcc.am.km.a(km.java:1963)
at com.ibm.db2.jcc.t4.db.g(db.java:139)
at com.ibm.db2.jcc.t4.db.a(db.java:39)
at com.ibm.db2.jcc.t4.t.a(t.java:32)
at com.ibm.db2.jcc.t4.sb.h(sb.java:135)
at com.ibm.db2.jcc.am.km.eb(km.java:1934)
at com.ibm.db2.jcc.am.lm.ic(lm.java:2798)
at com.ibm.db2.jcc.am.lm.b(lm.java:3517)
at com.ibm.db2.jcc.am.lm.Vb(lm.java:654)
at com.ibm.db2.jcc.am.lm.executeQuery(lm.java:628)
at filenet.pa.datacollector.LogQuery.query(Unknown Source)
at filenet.pa.datacollector.LogAgent.useLogQuery(Unknown Source)
at filenet.pa.datacollector.LogAgent.queryEvents(Unknown Source)
at filenet.pa.datacollector.LogAgent.getNextEvent(Unknown Source)
at filenet.pa.datacollector.LogAgent.getNextEvent(Unknown Source)
at filenet.pa.datacollector.EventDispatcher.run(Unknown Source)
at java.lang.Thread.run(Thread.java:801) 

Also found the same error message in the PA log.


CAUSE
Rebuilding the database views is not a typical step of procedure for deploying a user-defined data field. The database views looked not right after using the database's utility. Instead, vwtool is recommended tool.


DIAGNOSING THE PROBLEM
Reviewed the deployment procedure of the user-defined data field: 

 1. verified the data field was exposed in the queue, roster and event log using Process Configuration Console 
 2. verified the data field was created on PA in the PTM 
 3. found that database view was rebuilt by using database utility

RESOLVING THE PROBLEM
To fix the issue: 

 1. In the PE server, logon to vwtool as a PE admin user 
 2. run the command createDBviews to recreate the database views (if the database is local) or generate a database script (if the database is remote). 



Example: 
<vwtool:1>createDBviews 
Create : 
s - Creates script file containing the SQL statments 
required to create the DB views. 
(Must run this SQL script in the database to create views.) 
v - Create the views in the database. 
Choice? ('s', 'v'): s 
Work space id (CR = latest): 
File name without extension: c:\createDBviewscript 
DB User Name (CR=F_SW): sa 
The two following files are being created: 

c:\createDBviewscript.sql (sql script) 
c:\createDBviewscript.txt (description) 

Reference: 
Please refer to the topic createDBviews [http://publib.boulder.ibm.com/infocenter/p8docs/v4r5m1/index.jsp?topic=/com.ibm.p8.doc/pe_help/vwtool/createDBviews.htm] in the online info center for further details.