Title: IBM Pruning fails with error message: "java.sql.SQLException: [Microsoft][SQLServer 2000 Driver for JDBC] Can't start a cloned connection while in manual transaction mode." - United States

Text:
KB313181; pruning fails java.sql.SQLException Can't start cloned connection manual transaction mode SQLServer 2000 microsoft JDBC driver TECHNOTE (FAQ)

QUESTION
 The Summarization and Pruning process can fail with the above error message while using Microsoft SQL Server 2000 as Warehouse database. The *_sy_java_* log file contains an exception message. 

ANSWER
The following messages are visible in the *_sy_java_* log file: 

== 82 t=work1 work1 - Pruning data for table: (SIMULATORI_EVENTISIMULATORI00) and node: (robot3:SIMULATORI_EVENTI00)
== 83 t=work1 java.sql.SQLException: [Microsoft][SQLServer 2000 Driver for JDBC]Can't start a cloned connection while in manual transaction mode.
at com.microsoft.jdbc.base.BaseExceptions.createException(Unknown Source)
at com.microsoft.jdbc.base.BaseExceptions.getException(Unknown Source)
at com.microsoft.jdbc.base.BaseConnection.getImplConnection(Unknown Source)
at com.microsoft.jdbc.base.BaseStatement.setupImplConnection(Unknown Source)
at com.microsoft.jdbc.base.BaseStatement.<init>(Unknown Source)
at com.microsoft.jdbc.base.BasePreparedStatement.<init>(Unknown Source)
at com.microsoft.jdbc.base.BaseConnection.prepareStatement(Unknown Source)
at com.microsoft.jdbc.base.BaseConnection.prepareStatement(Unknown Source)
at com.tivoli.twh.ksy.db.WHPreparedStatement.buildSQL(WHPreparedStatement.java:725)
at com.tivoli.twh.ksy.db.WHPreparedStatement.executeUpdate(WHPreparedStatement.java:855)
at com.tivoli.twh.ksy.agg.Originnode.pruneDataForNode(Originnode.java:471)
at com.tivoli.twh.ksy.agg.RawTable.createAggregatesAndPrune(RawTable.java:3323)
at com.tivoli.twh.ksy.agg.Worker.run(Worker.java:118)

== 84 t=work1 SQL IN ERROR : 
statement name : SIMULATORI_EVENTISIMULATORI00_D.Del1
SQL : DELETE FROM "ITMUSER"."SIMULATORI_EVENTISIMULATORI00_D" WHERE "WRITETIME" = '1070612000000000' AND "Node_Name" = 'robot3:SIMULATORI_EVENTI00 ' 
template SQL : DELETE FROM "ITMUSER"."SIMULATORI_EVENTISIMULATORI00_D" WHERE "WRITETIME" = ? AND "Node_Name" = ? 
parameter #1 : ()
parameter #2 : ()
== 85 t=work1 com.tivoli.twh.ksy.core.KSYException
at com.tivoli.twh.ksy.db.WHPreparedStatement.buildSQL(WHPreparedStatement.java:730)
at com.tivoli.twh.ksy.db.WHPreparedStatement.executeUpdate(WHPreparedStatement.java:855)
at com.tivoli.twh.ksy.agg.Originnode.pruneDataForNode(Originnode.java:471)
at com.tivoli.twh.ksy.agg.RawTable.createAggregatesAndPrune(RawTable.java:3323)
at com.tivoli.twh.ksy.agg.Worker.run(Worker.java:118)

== 86 t=work1 EXCEPTION: Failed to prune data for node
== 87 t=work1 EXCEPTION: Failed to create aggregates and prune
== 88 t=work1 EXCEPTION: Failed to run worker 

 

The solution is to implement the changes to the JDBC driver configuration as detailed in the Microsoft article KB313181 that can be accessed at the following link: 


http://support.microsoft.com/kb/313181 [http://support.microsoft.com/kb/313181]