Title: IBM Error Message "BMXAA3851E - connecting to the server has been disabled" during Login - United States

Text:
TPAEUI; BMXAA3851E; connecting to the server has been disabled TECHNOTE (TROUBLESHOOTING)

PROBLEM(ABSTRACT)
 None of the users can login to Maximo. Admin mode is OFF and there is no pending database configuration. 

SYMPTOM
Below is the error message that comes up when the users are trying to log in to Maximo: 

[/support/docview.wss?uid=swg21993048&aid=1] [/support/docview.wss?uid=swg21993048&aid=1]

There is no error in the systemout.log and systemerr.log files. 

- Set the SQL log level to INFO in the maxlogger table via the backend:

update maxlogger set loglevel='INFO' where logger ='sql' and logkey='log4j.logger.maximo.sql'

[/support/docview.wss?uid=swg21993048&aid=2] [/support/docview.wss?uid=swg21993048&aid=2]


- Notice that the "appenders" column is set to Rolling. So the SQL log is being sent to maximo.log (and not systemout.log)
- Run the query below to find out the location of maximo.log:
select * from maxpropvalue where propname like '%rootfolder'

[/support/docview.wss?uid=swg21993048&aid=3] [/support/docview.wss?uid=swg21993048&aid=3]


- The screenshot shows that the maximo.log resides under c:\temp\maximo\logs

Below is an excerpt from the maximo.log file:

[ BMXAA6694W - The mbovalueinfo for attribute &SYSDATE& for object LOGINTRACKING could not be retrieved.
psdi.util.MXSystemException: BMXAA6694W - The mbovalueinfo for attribute &SYSDATE& for object LOGINTRACKING could not be retrieved.
at psdi.mbo.Mbo.getMboValueInfo(Mbo.java:1220)
at psdi.mbo.Mbo.getMboValue(Mbo.java:1179)
at psdi.mbo.Mbo.getDate(Mbo.java:2289)
at psdi.common.parse.AttributeNode.getDate(AttributeNode.java:126)
at psdi.common.parse.ParserService.getDate(ParserService.java:249)
at psdi.mbo.Mbo.setDatabaseDefaultValues(Mbo.java:4932)
at psdi.mbo.MboSet.addAtIndex(MboSet.java:4687)
at psdi.mbo.MboSet.add(MboSet.java:4595)
at psdi.app.signature.MaxUser.addLoginTracking(MaxUser.java:1498)

[ BMXAA6719I - USER = (MAXADMIN) object (SYNONYMDOMAIN) : select * from synonymdomain where ((value= 'LOGIN' and siteid is null and orgid is null ) and (domainid = 'ATTEMPTRESULT' and siteid is null and orgid is null )) and (rownum<=1000)
[BMXAA6719I - USER = (MAXADMIN) object (MAXATTRIBUTE) : select * from maxattribute where objectname='LOGINTRACKING' order by objectname
BMXAA4190E - Attempt Result LOGIN is not in the value list.
psdi.util.MXApplicationException: BMXAA4190E - Attempt Result LOGIN is not in the value list.
at psdi.mbo.MAXTableDomain.validate(MAXTableDomain.java:166)
at psdi.mbo.MboValue.validate(MboValue.java:1708)
at psdi.mbo.MboValue.setValue(MboValue.java:900)
at psdi.mbo.MboValue._setValue(MboValue.java:1255)
at psdi.mbo.MboValue.setValue(MboValue.java:1151)
at psdi.mbo.Mbo.setValue(Mbo.java:2361)
at psdi.mbo.Mbo.setValue(Mbo.java:2462)
at psdi.app.signature.MaxUser.addLoginTracking(MaxUser.java:1502)


CAUSE
- Run the query recorded in the log directly against the database:

select * from synonymdomain where ((value= 'LOGIN' and siteid is null and orgid is null ) 
and (domainid = 'ATTEMPTRESULT' and siteid is null and orgid is null ))
- No record has been returned. 

- Remove "siteid is null and orgid is null" from the query above and re-run the query:
select * from synonymdomain where value= 'LOGIN' and domainid = 'ATTEMPTRESULT'
One record has been returned:

[/support/docview.wss?uid=swg21993048&aid=4] [/support/docview.wss?uid=swg21993048&aid=4]


- We need to remove both the ORGID and SITEID in the Attemptresult domain so that the query recorded in the log will run successfully.


RESOLVING THE PROBLEM
- Remove the ORGID and SITEID from the ATTEMPTRESULT synonymdomain. 

update synonymdomain set orgid=NULL , siteid=NULL 
where value= 'LOGIN' and domainid = 'ATTEMPTRESULT'

- Now run the same query again:
select * from synonymdomain where ((value= 'LOGIN' and siteid is null and orgid is null ) 
and (domainid = 'ATTEMPTRESULT' and siteid is null and orgid is null ))

- The query returns one record:

[/support/docview.wss?uid=swg21993048&aid=5] [/support/docview.wss?uid=swg21993048&aid=5]
- Now that the query returns a record, all the users can now log in to Maximo without any error.