Title: IBM Performing Case Foundation Process Engine upgrade results in error [FNRPE2131090440E]Unable to instantiate archiver class number 0 - United States

Text:
JDBC driver; F_Blob; Classpath TECHNOTE (TROUBLESHOOTING)

PROBLEM(ABSTRACT)
 While performing Process Engine upgrade receive the error [FNRPE2131090440E]Unable to instantiate archiver class number 0 

SYMPTOM
When performing a Process Engine 4.5.1 to CPE 5.2.1 upgrade the following error is seen in the peupgrade_out file:

PEUpgrade task id 1

..
Upgrade has failed, check the log for more details. [FNRPE2131090440E]Unable to instantiate archiver class number 0
Caused by corrupted data or failure to upgrade database software prior to running a new release
Upgrade has failed, check the log for more details. [FNRPE2131090440E]Unable to instantiate archiver class number 0
Caused by corrupted data or failure to upgrade database software prior to running a new release
Upgrade has failed, check the log for more details.
Task 1 terminated


Running the traceOptions logging, the following is seen in the pesvr_trace.log file:


TaskManager PESe DB=FNSW [Trace] DBI_MSGS, SQL executed in 2.4 msecs, prep=1, timeout=0, con=0a7bbe93: "SELECT F_Blob, F_ObjName, F_ObjInt, F_Flags FROM f_sw.VWObject where F_ObjName = ? ", params="farm.config"
TaskManager PESec DB=FNSW [Trace] DBI_OUT, DbResult next = true
TaskManager PESec DB=FNSW [Trace] DBI_OUT, DbResult get bytes(0) = 0x.....
....
RPCHandler pool-15-thread-2 DB=FNSW [Error] FNRPE2131090440E Upgrade has failed, check the log for more details. [FNRPE2131090440E]Unable to instantiate archiver class number 0
Caused by corrupted data or failure to upgrade database software prior to running a new release; Exception: Unable to instantiate archiver class number 0
Caused by corrupted data or failure to upgrade database software prior to running a new release
at filenet.jpe.general.VArchiver.archGetObject(VArchiver.java:382)
at filenet.jpe.database.DbRecord.UnloadBlob(DbRecord.java:569)
at filenet.jpe.database.DbRecord.unloadBlob(DbRecord.java:557)
at filenet.jpe.objectservice.ObjectService.readObject(ObjectService.java:1534)
at filenet.jpe.objectservice.ObjectService.findObject(ObjectService.java:1326)
at filenet.jpe.server.common.ConfigData.ReadConfigFromDB(ConfigData.java:358)
at filenet.jpe.general.INIMan.ReadIniConfigFromDB(INIMan.java:252)
at filenet.jpe.general.INIMan.CreateFromDB(INIMan.java:288)
at filenet.jpe.server.common.ServerDBContext.refreshINIMan(ServerDBContext.java:566)
at filenet.jpe.server.upgrade.PEUpgrade.upgradeServer(PEUpgrade.java:357)
at filenet.jpe.server.upgrade.PEUpgrade.startUpgrade(PEUpgrade.java:271)
at filenet.jpe.server.upgrade.PEUpgrade.run(PEUpgrade.java:9404)
at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
at java.lang.Thread.run(Thread.java:790)
Caused by: java.lang.NullPointerException
at filenet.jpe.general.VArchiver.archGetObject(VArchiver.java:378)
... 14 more


CAUSE
The JDBC driver classpath is incorrectly specified in WebSphere Administrative Console which is preventing the F_Blob from being read correctly during the upgrade:

${ORACLE_JDBC_DRIVER_PATH}/
ojdbc6.jar

when it should be all on the same line:

${ORACLE_JDBC_DRIVER_PATH}/ojdbc6.jar

Otherwise it will read the first jar file in the directory

DIAGNOSING THE PROBLEM
Looking at the pesvr_trace.log we see that the F_Blob output "DbResult get bytes(0) = " of the farm.config parameter in the VWObject table is not the same as what is returned when we run a vwtool:1>dump of the same select statement: "SELECT F_Blob FROM dbo.VWObject WHERE F_ObjName='farm.config'" directly from the 4.5 system.

Make sure to obtain the CPE ping page: http://<cpe-server name>:<cpe-port #>/FileNet/Engine and look at the JDBC driver entry. In this case it showed:

Oracle JDBC driver 10.1.0.2.0 loaded from file:/opt/jdbc/oracle/classes12.jar

This is the incorrect driver. Having the jar file on the preceding line in the classpath causes it to read the first jar file in the directory.

RESOLVING THE PROBLEM
1. Open WebSphere's Administrative Console.
2. Navigate to Resources -> JDBC -> JDBC Providers
3. Locate the JDBC driver that you are using for CPE.
4. Edit the JDBC driver.
5. Go to the Classpath section.
6. Verify that the path is correct and the driver jar file is on the same line as the JDBC driver path. Make any necessary changes.
7. Restart WebSphere.
8. Re-run the Process Engine upgrade.