Title: IBM Attempting to create a replication group can result in an ambiguous error which is caused by a lack of DB tablespace - United States

Text:
 TECHNOTE (TROUBLESHOOTING)

PROBLEM(ABSTRACT)
 Attempt to create replication group in FileNet Enterprise Manager fails stating database access has failed which prevents the use of Content Federation. The error does not specify the root cause but mentions that a call to getNextException() could produce the root problem description.





ENVIRONMENT
DB2

DIAGNOSING THE PROBLEM
When attempting to create replication group, FEM returns the following error:

File = .\AdmReplicationHelper.cpp, Line = 1851, Rev. = $Revision: 1.21 $

Source =
Description = The database access failed with the following error:
ErrorCode -4,229, Message '[jcc][t4][102][10040][3.64.133] Batch
failure. The batch was submitted, but at least one exception occurred
on an individual member of the batch.
Use getNextException() to retrieve the exceptions for specific batched
elements. ERRORCODE=-4229, SQLSTATE=null' SQL: "INSERT INTO
ReplicationQueue (object_id, object_class_id, security_id, epoch_id,
creator, create_date, modify_user, modify_date, source_object_id,
source_object_id_class, destination_id, destination_id_class,
exclusion_id, replication_group_id, operation, serialized_data,
retry_count, lease_count, status, seqnum_identity, held_until_date)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
NEXTVAL FOR ReplSequence, (CURRENT TIMESTAMP - CURRENT TIMEZONE))" In-
bindings: ({53198246-2A92-48FB-A920-F394C08AAD82},{A89D289C-708C-45EE-
9A97-8C756D11F2A6},{00000000-0000-0000-0000-000000000000},1,'Y988321',
Thu Sep 03 13:01:30 CEST 2015,'Y988321',Thu Sep 03 13:01:30 CEST 2015,
{9333B7AB-4084-488D-8F3B-3CF10D2185CA},{D78C19AD-A74A-4C43-AD9B-
46D4A9B2D843},{66DDC6D0-E766-4054-826D-FF409C3F45CA},{53ECE6B4-DD95-
4010-848E-5670E6CB0B5C},{9333B7AB-4084-488D-8F3B-3CF10D2185CA},
{9333B7AB-4084-488D-8F3B-3CF10D2185CA},4,[len=469]
0xaced00057372004e636f6d2e66696c656e65742e656e67696e652e7265706c69...,
0,0,0). [jcc][t4][102][10040][3.64.133] Batch failure. The batch was
submitted, but at least one exception occurred on an individual member
of the batch.
Use getNextException() to retrieve the exceptions for specific batched
elements. ERRORCODE=-4229, SQLSTATE=null.
--------
Error Code: 0
Error Source: FileNet.Api

HR = 0x800710d9
HR Description = Unable to read from or write to the database.
MinorCode = 0x00000a94 

The p8_server_error.log shows:

2015-09-17T13:42:48.622Z 76EE76EE ENG FNRCD0009E - ERROR A failure occurred attempting to request ExternalParticipant providers for ReplicationGroup change.
com.filenet.api.exception.EngineRuntimeException: FNRCD0009E: DB_ERROR: The database access failed with the following error: ErrorCode -4,229, Message '[jcc][t4][102][10040][3.64.133] Batch failure. The batch was submitted, but at least one exception occurred on an individual member of the batch.
Use getNextException() to retrieve the exceptions for specific batched elements. ERRORCODE=-4229, SQLSTATE=null' SQL: "INSERT INTO ReplicationQueue (object_id, object_class_id, security_id, epoch_id, creator, create_date, modify_user, modify_date, source_object_id, source_object_id_class, destination_id, destination_id_class, exclusion_id, replication_group_id, operation, serialized_data, retry_count, lease_count, status, seqnum_identity, held_until_date) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, NEXTVAL FOR ReplSequence, (CURRENT TIMESTAMP - CURRENT TIMEZONE))" In-bindings: ({C8880419-8C7D-4E7B-9234-CCB7B52E641D},{A89D289C-708C-45EE-9A97-8C756D11F2A6},{00000000-0000-0000-0000-000000000000},1,'Y988321',Thu Sep 17 15:42:48 CEST 2015,'Y988321',Thu Sep 17 15:42:48 CEST 2015,{633DF90A-7273-45DD-A27B-CC5F49264BB1},{D78C19AD-A74A-4C43-AD9B-46D4A9B2D843},{66DDC6D0-E766-4054-826D-FF409C3F45CA},{53ECE6B4-DD95-4010-848E-5670E6CB0B5C},{633DF90A-7273-45DD-A27B-CC5F49264BB1},{633DF90A-7273-45DD-A27B-CC5F49264BB1},4,[len=469] 0xaced00057372004e636f6d2e66696c656e65742e656e67696e652e7265706c69...,0,0,0)
at com.filenet.engine.dbpersist.DBDB2Context.throwEngineException(DBDB2Context.java:814)
at com.filenet.engine.dbpersist.DBStatementBase.executeBatch(DBStatementBase.java:328)
at com.filenet.engine.replication.ReplicationJournalWriter.writeGroupConfirmation(ReplicationJournalWriter.java:259)
at com.filenet.engine.persist.ReplicationGroupPersister.issueChangeRequests(ReplicationGroupPersister.java:451)
at com.filenet.engine.persist.ReplicationGroupPersister.postExecuteChange(ReplicationGroupPersister.java:258)
at com.filenet.engine.persist.BaseGCDPersister.executeChangeWork(BaseGCDPersister.java:269)
at com.filenet.engine.persist.IndependentPersister.executeChange(IndependentPersister.java:229)
at com.filenet.engine.persist.BaseGCDPersister.executeChange(BaseGCDPersister.java:129)
at com.filenet.engine.jca.impl.RequestBrokerImpl.executeChanges(RequestBrokerImpl.java:1278)
at com.filenet.engine.jca.impl.RequestBrokerImpl.executeChanges(RequestBrokerImpl.java:1158)
at com.filenet.engine.ejb.EngineCoreBean._executeChanges(EngineCoreBean.java:618)
at com.filenet.engine.ejb.EngineCoreBean.executeChanges(EngineCoreBean.java:586)
at com.filenet.engine.ejb.EJSLocalStatelessEngineCore_22877cb1.executeChanges(Unknown Source)
at com.filenet.engine.ejb.EngineBean.executeChanges(EngineBean.java:832)
at com.filenet.apiimpl.transport.ejbstubs.EJSLocalStatelessEngine_2e64c374.executeChanges(Unknown Source)
at com.filenet.apiimpl.transport.ejb.EnginePortLocal.executeChanges(EnginePortLocal.java:53)
at com.filenet.apiimpl.wsi.ServiceSessionNst$2.run(ServiceSessionNst.java:1244)
at java.security.AccessController.doPrivileged(AccessController.java:310)
at javax.security.auth.Subject.doAs(Subject.java:573)
at com.ibm.websphere.security.auth.WSSubject.doAs(WSSubject.java:194)
at com.ibm.websphere.security.auth.WSSubject.doAs(WSSubject.java:151)
at sun.reflect.GeneratedMethodAccessor52.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:37)
at java.lang.reflect.Method.invoke(Method.java:611)
at com.filenet.apiimpl.util.J2EEUtilWS.doAs(J2EEUtilWS.java:215)
at com.filenet.apiimpl.wsi.ServiceSessionNst.sMakeInternalEJBCall(ServiceSessionNst.java:1074)
at com.filenet.apiimpl.wsi.ServiceSessionNst.sHandleIncomingRequest(ServiceSessionNst.java:994)
at com.filenet.engine.wsi.ListenerNst.service(ListenerNst.java:163)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:831)
at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1657)
at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:939)
at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:502)
at com.ibm.ws.webcontainer.servlet.ServletWrapperImpl.handleRequest(ServletWrapperImpl.java:181)
at com.ibm.ws.webcontainer.servlet.CacheServletWrapper.handleRequest(CacheServletWrapper.java:91)
at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:864)
at com.ibm.ws.webcontainer.WSWebContainer.handleRequest(WSWebContainer.java:1592)
at com.ibm.ws.webcontainer.channel.WCChannelLink.ready(WCChannelLink.java:186)
at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:452)
at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.handleNewRequest(HttpInboundLink.java:511)
at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.processRequest(HttpInboundLink.java:305)
at com.ibm.ws.http.channel.inbound.impl.HttpICLReadCallback.complete(HttpICLReadCallback.java:83)
at com.ibm.ws.tcp.channel.impl.AioReadCompletionListener.futureCompleted(AioReadCompletionListener.java:165)
at com.ibm.io.async.AbstractAsyncFuture.invokeCallback(AbstractAsyncFuture.java:217)
at com.ibm.io.async.AsyncChannelFuture.fireCompletionActions(AsyncChannelFuture.java:161)
at com.ibm.io.async.AsyncFuture.completed(AsyncFuture.java:138)
at com.ibm.io.async.ResultHandler.complete(ResultHandler.java:204)
at com.ibm.io.async.ResultHandler.runEventProcessingLoop(ResultHandler.java:775)
at com.ibm.io.async.ResultHandler$2.run(ResultHandler.java:905)
at com.ibm.ws.util.ThreadPool$Worker.run(ThreadPool.java:1646)
Caused by: com.ibm.db2.jcc.am.BatchUpdateException: [jcc][t4][102][10040][3.64.133] Batch failure. The batch was submitted, but at least one exception occurred on an individual member of the batch.
Use getNextException() to retrieve the exceptions for specific batched elements. ERRORCODE=-4229, SQLSTATE=null
at com.ibm.db2.jcc.am.bd.a(bd.java:407)
at com.ibm.db2.jcc.am.Agent.endBatchedReadChain(Agent.java:399)
at com.ibm.db2.jcc.am.jo.a(jo.java:5030)
at com.ibm.db2.jcc.am.jo.c(jo.java:4620)
at com.ibm.db2.jcc.am.jo.executeBatch(jo.java:2909)
at com.ibm.ws.rsadapter.jdbc.WSJdbcPreparedStatement.pmiExecuteBatch(WSJdbcPreparedStatement.java:1012)
at com.ibm.ws.rsadapter.jdbc.WSJdbcStatement.executeBatch(WSJdbcStatement.java:822)
at com.filenet.engine.dbpersist.DBStatementBase.executeBatch(DBStatementBase.java:309)
... 47 more



RESOLVING THE PROBLEM
Obtaining the db2support command output to DB2 support provided the following solution:
Root cause of error is a table space issue. 

It showed that SQLCODE=-1476, SQLSTATE=40506, SQLERRMC=-289 lead to
http://www-01.ibm.com/support/knowledgecenter/SSEPGG_10.5.0/com.ibm.db2.luw.messages.sql.doc/doc/msql00289n.html [http://www-01.ibm.com/support/knowledgecenter/SSEPGG_10.5.0/com.ibm.db2.luw.messages.sql.doc/doc/msql00289n.html]


RELATED INFORMATION
 SQL Code -289 Documentation [http://www-01.ibm.com/support/knowledgecenter/SSEPGG_10.5.0/com.ibm.db2.luw.messages.sql.doc/doc/msql00289n.html]